package fr.fillatre.springboot.issue;

import com.example.config.ShutdownApplicationListener;
import com.example.config.StartupApplicationListener;

import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigurationExcludeFilter;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.boot.context.TypeExcludeFilter;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.ComponentScan.Filter;
import org.springframework.context.annotation.FilterType;
import org.springframework.context.annotation.Import;

@SpringBootConfiguration
@ComponentScan(excludeFilters = {
        @Filter(type = FilterType.CUSTOM, classes = TypeExcludeFilter.class),
        @Filter(type = FilterType.CUSTOM, classes = AutoConfigurationExcludeFilter.class) })
@Import({ org.springframework.boot.actuate.autoconfigure.AuditAutoConfiguration.class,
        org.springframework.cloud.sleuth.zipkin.ZipkinAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.CacheStatisticsAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.CrshAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.EndpointAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.EndpointMBeanExportAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.EndpointWebMvcAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.EndpointWebMvcHypermediaManagementContextConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.EndpointWebMvcManagementContextConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.HealthIndicatorAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.InfoContributorAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.JolokiaAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.ManagementServerPropertiesAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.ManagementWebSecurityAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.MetricExportAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.MetricFilterAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.MetricRepositoryAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.MetricsChannelAutoConfiguration.class,
        // org.springframework.boot.actuate.autoconfigure.MetricsDropwizardAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.PublicMetricsAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.TraceRepositoryAutoConfiguration.class,
        org.springframework.boot.actuate.autoconfigure.TraceWebFilterAutoConfiguration.class,
        // org.springframework.boot.actuate.cloudfoundry.CloudFoundryActuatorAutoConfiguration.class,
        org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration.class,
        org.springframework.boot.autoconfigure.aop.AopAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.cloud.CloudAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.context.MessageSourceAutoConfiguration.class,
        org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.couchbase.CouchbaseAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.dao.PersistenceExceptionTranslationAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.cassandra.CassandraRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.couchbase.CouchbaseDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.couchbase.CouchbaseRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.ldap.LdapDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.ldap.LdapRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.mongo.MongoRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.neo4j.Neo4jDataAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.neo4j.Neo4jRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.rest.RepositoryRestMvcAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.solr.SolrRepositoriesAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.elasticsearch.jest.JestAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.gson.GsonAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.hateoas.HypermediaAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.hazelcast.HazelcastJpaDependencyAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.integration.IntegrationAutoConfiguration.class,
        org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jdbc.JndiDataSourceAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jdbc.XADataSourceAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jersey.JerseyAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jms.JndiConnectionFactoryAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jms.artemis.ArtemisAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.ldap.LdapAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.ldap.embedded.EmbeddedLdapAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mail.MailSenderValidatorAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mobile.DeviceDelegatingViewResolverAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mobile.DeviceResolverAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mobile.SitePreferenceAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.mustache.MustacheAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.reactor.ReactorAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.security.FallbackWebSecurityAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.security.SecurityFilterAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.security.oauth2.OAuth2AutoConfiguration.class,
        // org.springframework.boot.autoconfigure.sendgrid.SendGridAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.session.SessionAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.social.FacebookAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.social.LinkedInAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.social.SocialWebAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.social.TwitterAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.transaction.jta.JtaAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.validation.ValidationAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.DispatcherServletAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.EmbeddedServletContainerAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.HttpEncodingAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.HttpMessageConvertersAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.MultipartAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.ServerPropertiesAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.WebClientAutoConfiguration.class,
        org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration.class,
        // org.springframework.boot.autoconfigure.webservices.WebServicesAutoConfiguration.class,
        org.springframework.boot.autoconfigure.websocket.WebSocketAutoConfiguration.class,
        org.springframework.boot.autoconfigure.websocket.WebSocketMessagingAutoConfiguration.class,
        // org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration.class,
        // org.springframework.boot.devtools.autoconfigure.LocalDevToolsAutoConfiguration.class,
        // org.springframework.boot.devtools.autoconfigure.RemoteDevToolsAutoConfiguration.class,
        org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.class,
        org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration.class,
        org.springframework.cloud.autoconfigure.RefreshAutoConfiguration.class,
        org.springframework.cloud.autoconfigure.RefreshEndpointAutoConfiguration.class,
        org.springframework.cloud.client.CommonsClientAutoConfiguration.class,
        org.springframework.cloud.client.discovery.noop.NoopDiscoveryClientAutoConfiguration.class,
        // org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration.class,
        // org.springframework.cloud.client.hypermedia.CloudHypermediaAutoConfiguration.class,
        org.springframework.cloud.client.loadbalancer.AsyncLoadBalancerAutoConfiguration.class,
        org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration.class,
        // org.springframework.cloud.client.serviceregistry.ServiceRegistryAutoConfiguration.class,
        org.springframework.cloud.commons.util.UtilAutoConfiguration.class,
        org.springframework.cloud.config.client.ConfigClientAutoConfiguration.class,
        org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration.class,
        org.springframework.cloud.netflix.feign.FeignAutoConfiguration.class,
        org.springframework.cloud.netflix.feign.encoding.FeignAcceptGzipEncodingAutoConfiguration.class,
        org.springframework.cloud.netflix.feign.encoding.FeignContentGzipEncodingAutoConfiguration.class,
        org.springframework.cloud.netflix.feign.ribbon.FeignRibbonClientAutoConfiguration.class,
        org.springframework.cloud.netflix.hystrix.HystrixAutoConfiguration.class,
        org.springframework.cloud.netflix.hystrix.security.HystrixSecurityAutoConfiguration.class,
        org.springframework.cloud.netflix.metrics.MetricsInterceptorConfiguration.class,
        org.springframework.cloud.netflix.metrics.servo.ServoMetricsAutoConfiguration.class,
        org.springframework.cloud.netflix.metrics.spectator.SpectatorMetricsAutoConfiguration.class,
        org.springframework.cloud.netflix.ribbon.RibbonAutoConfiguration.class,
        org.springframework.cloud.netflix.rx.RxJavaAutoConfiguration.class,
        // org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration.class,
        // org.springframework.cloud.netflix.zuul.ZuulServerAutoConfiguration.class,
        // org.springframework.cloud.sleuth.annotation.SleuthAnnotationAutoConfiguration.class,
        org.springframework.cloud.sleuth.autoconfig.TraceAutoConfiguration.class,
        // org.springframework.cloud.sleuth.instrument.async.AsyncCustomAutoConfiguration.class,
        // org.springframework.cloud.sleuth.instrument.async.AsyncDefaultAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixAutoConfiguration.class,
        // org.springframework.cloud.sleuth.instrument.messaging.TraceSpanMessagingAutoConfiguration.class,
        // org.springframework.cloud.sleuth.instrument.messaging.TraceSpringIntegrationAutoConfiguration.class,
        // org.springframework.cloud.sleuth.instrument.messaging.websocket.TraceWebSocketAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.rxjava.RxJavaAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.scheduling.TraceSchedulingAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.web.TraceHttpAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.web.client.TraceWebAsyncClientAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.web.client.TraceWebClientAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.web.client.feign.TraceFeignClientAutoConfiguration.class,
        org.springframework.cloud.sleuth.instrument.zuul.TraceZuulAutoConfiguration.class,
        org.springframework.cloud.sleuth.log.SleuthLogAutoConfiguration.class,
        org.springframework.cloud.sleuth.metric.TraceMetricsAutoConfiguration.class })
public class ExplicitImportWithoutUnmatchedApplication {

    public static void main(String[] args) {
        new SpringApplicationBuilder(ExplicitImportWithoutUnmatchedApplication.class)
                .listeners(
                        new StartupApplicationListener(
                                ExplicitImportWithoutUnmatchedApplication.class),
                        new ShutdownApplicationListener(
                                ExplicitImportWithoutUnmatchedApplication.class))
                .run(args);
    }
}
